const ABOUT_SKILLS = {
  programmingLanguage: [
    "javaScript",
    "typeScript",
    "python",
    "java",
    "c",
    "html",
    "css",
    "scss",
    "sql",
  ],
  frontend: [
    "react",
    "reactnative",
    "nextjs",
    "reactrouter",
    "shadcnui",
    "tailwindcss",
    "bootstrap",
  ],
  backend: ["fastapi", "strapi", "expressjs", "django", "flask", "firebase"],
  authenticationSecurity: [
    "clerk",
    "firebaseauthentication",
    "jwt",
    "oauth",
    "ssl",
  ],
  database: [
    "mysql",
    "postgresql",
    "sqlite",
    "mongodb",
    "firestore",
    "prisma",
    "sqlalchemy",
  ],
  devOpsInfra: [
    "docker",
    "nginx",
    "ubuntuserver",
    "gitgitcli",
    "github",
    "digitalocean",
    "vercel",
    "libgdx",
  ],
};

export default ABOUT_SKILLS;
