const PROJECT_CONTENT = [
  {
    title: "Bloom",
    description:
      "A fully responsive and customizable developer portfolio built with React and React Router (Framework Mode). Designed to showcase projects, skills, and personal branding, the portfolio supports clean routing, smooth UI transitions, and a theme-friendly design that reflects both aesthetics and performance.",
    date: "2025/05 ~ Present",
    image: "image1.jpg",
    gitHubLink: null,
    hostedLink: null,
    techStack: ["react", "nextjs", "tailwindcss", "shadcnui"],
    roles: ["Full-Stack Developer", "UI/UX Designer", "Project Manager"],
    teamSize: 5,
    highlight: true,
    whatIDid: [
      "Led the architecture and development of an all-in-one study abroad platform for Japanese users",
      "Designed a flexible content model with Strapi to efficiently manage diverse information",
      "Acted as a key communicator with Japanese stakeholders to align project goals with user needs",
    ],
  },
  {
    title: "Hiragana",
    description:
      "A fully responsive and customizable developer portfolio built with React and React Router (Framework Mode). Designed to showcase projects, skills, and personal branding, the portfolio supports clean routing, smooth UI transitions, and a theme-friendly design that reflects both aesthetics and performance.",
    date: "2025/06 ~ Present",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/hiragana.git",
    hostedLink: null,
    techStack: ["reactnative", "tailwindcss"],
    roles: ["Mobile Development"],
    teamSize: 2,
    highlight: true,
    whatIDid: [
      "Designed and developed a gamified Japanese learning mobile app using React Native",
      "Orchestrated the end-to-end development of a Japanese learning app, from initial concept to launch",
      "Engineered a quest-based progression system with animated characters to boost user motivation",
      "Crafted an intuitive interface that provides clear, immediate feedback through interactive animations",
    ],
  },
  {
    title: "Portfolio",
    description:
      "A fully responsive and customizable developer portfolio built with React and React Router (Framework Mode). Designed to showcase projects, skills, and personal branding, the portfolio supports clean routing, smooth UI transitions, and a theme-friendly design that reflects both aesthetics and performance.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/portfolio.git",
    hostedLink: "https://anthonydev.me",
    techStack: ["react", "reactrouter", "tailwindcss", "shadcnui"],
    roles: ["Full-Stack Developer", "UI/UX Designer"],
    teamSize: 1,
    highlight: true,
    whatIDid: [
      "Designed and developed a modular, fully responsive portfolio site using React and React Router (Framework Mode).",
      "Implemented a clean component architecture that separates content (JSON-based) from presentation for easy scalability and customization.",
      "Built reusable UI components with Tailwind CSS and ShadCN/UI to ensure design consistency and maintainability.",
      "Integrated theme-aware design (light/dark mode) with OKLCH color space support for precise color control.",
      "Optimized routing performance and scroll behavior to improve navigation and user experience.",
    ],
  },
  {
    title: "Skyline Zipline Inspection",
    description:
      "A full-featured inspection management system for Skyline Zipline. The platform enables zipline operators to record, track, and manage inspection data across multiple sites with real-time updates and optimized data integrity. Designed with usability and scalability in mind, it features role-based access and a clean interface for efficient day-to-day operations.",
    date: "2025/01 ~ 2025/4",
    image: "image1.jpg",
    gitHubLink: null,
    hostedLink: "https://skyline-zipline-inspection.vercel.app/login",
    techStack: [
      "react",
      "nextjs",
      "firebase",
      "mysql",
      "tailwindcss",
      "shadcnui",
      "reactnative",
      "python",
      "fastapi",
    ],
    roles: ["Full-Stack Developer", "Project Manager", "Database Designer"],
    teamSize: 3,
    highlight: true,
    whatIDid: [
      "Architected a full-stack inspection application using Next.js, React Native, and Firebase",
      "Resolved Firestore query limitations by leading a migration to SQL, enhancing backend performance",
      "Acted as the primary point of contact for clients, leading meetings to define project scope and requirements",
      "Led a 3-person development team, delegating tasks and managing workloads to meet sprint goals",
      "Created database schemas and relationships for efficient storage and retrieval of inspection records using MySQL.",
      "Configured environment variables and deployment processes for Firebase and custom domain hosting.",
    ],
  },
  {
    title: "Dash to the Finish",
    description:
      "A solo board game built with LibGDX where the player navigates a grid-based map from start to finish. Random events like +1/+2 movement or mini-games appear along the way. Winning a mini-game moves the player forward, while losing sends them back. The game offers a simple yet engaging experience powered by LibGDX’s robust 2D game framework.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/Dash-to-the-Finish.git",
    hostedLink: null,
    techStack: ["java", "LibGDX"],
    roles: ["Game Logic Developer", "UI Designer"],
    teamSize: 2,
    highlight: true,
    whatIDid: [
      "Designed and implemented a solo board game using Java and LibGDX, featuring grid-based movement and random events.",
      "Developed core game mechanics including +1/+2 tile effects and mini-game triggers to introduce unpredictability and strategy.",
      "Created and managed mini-games within the main game flow, allowing players to advance or retreat based on results.",
      "Utilized LibGDX to handle rendering, input management, and game loop optimization for a smooth gameplay experience.",
      "Structured the codebase using modular design principles for improved maintainability and scalability.",
    ],
  },
  {
    title: "The Path of Japan",
    description:
      "A command-line adventure game that guides players through iconic locations in Japan with interactive storytelling. Despite its text-based nature, the game focuses on user-friendly design, enhancing the experience through structured UI elements and smooth navigation.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/The-Path-of-Japan.git",
    hostedLink: null,
    techStack: ["python"],
    roles: ["Game Logic Developer"],
    teamSize: 2,
    highlight: true,
    whatIDid: [
      "Designed and developed a modular command-line adventure game featuring multiple branching storylines and dynamic interactions.",
      "Focused on atomic function design and modular architecture to ensure scalability and maintainability.",
      "Utilized libraries such as Colorama and cfonts to enhance visual clarity and readability within the terminal.",
      "Applied BeautifulSoup and dashtable for data formatting and clean display of location details and choices.",
      "Crafted a user-friendly CLI layout to improve navigation, feedback visibility, and overall player engagement.",
    ],
  },
  {
    title: "Rate Van Rent",
    description:
      "A web application that helps renters in Vancouver share and explore honest reviews about rental properties. Users can submit their experiences, evaluate properties through thumbs-up or thumbs-down, and make more informed rental decisions based on community feedback.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/Rate-Van-Rent.git",
    hostedLink: "https://comp1800-demo-202330-edro.web.app/",
    techStack: ["html", "css", "firebase", "firestore", "bootstrap"],
    roles: ["Full-Stack Developer", "Database Designer"],
    teamSize: 3,
    highlight: true,
    whatIDid: [
      "Built the full application from front to back using vanilla JavaScript, HTML/CSS, and Bootstrap for UI design.",
      "Designed and structured Firestore database schema to store user reviews and rating metadata effectively.",
      "Implemented real-time thumbs-up/thumbs-down voting functionality to increase credibility of user-submitted reviews.",
      "Developed robust form validation to ensure input quality and prevent incomplete or incorrect submissions.",
    ],
  },
  {
    title: "Dinosaur Hangman",
    description:
      "A fun, single-page word guessing game where players try to save a dinosaur from extinction by correctly guessing letters. Built with JavaScript, jQuery, and SCSS, the game features responsive design, keyboard controls, sound effects, and playful animations for an engaging user experience.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://github.com/shinn92dev/project-hangman-comp2132.git",
    hostedLink: null,
    techStack: ["html", "scss", "js", "jquery"],
    roles: ["Front-End Developer", "Game Logic Developer"],
    teamSize: 1,
    highlight: false,
    whatIDid: [
      "Developed a fully interactive single-page Hangman game using JavaScript and jQuery for game logic and DOM manipulation.",
      "Implemented keyboard input support for seamless gameplay and enhanced accessibility.",
      "Designed responsive UI and added subtle shaking animations using SCSS to provide visual feedback on wrong guesses.",
      "Integrated sound effects for correct and incorrect guesses to create a more engaging user experience.",
    ],
  },
];

export default PROJECT_CONTENT;
