const PROJECT_CONTENT = [
  {
    title: "Portfolio",
    description: "Description 1",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: null,
    hostedLink: "https://www.google.com",
    techStack: ["react", "reactrouter"],
    roles: null,
    teamSize: 1,
    highlight: true,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
  {
    title: "Skyline Zipline Inspection",
    description: "Description 1",
    date: "2025/01 ~ 2025/5",
    image: "image1.jpg",
    gitHubLink: null,
    hostedLink: "https://www.google.com",
    techStack: ["react", "nextjs", "firebase", "mysql"],
    roles: ["Full-Stack Developer", "Project Manager"],
    teamSize: 3,
    highlight: true,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
  {
    title: "Dash to the Finish",
    description:
      "a board game where players start in the bottom corner and navigate around the board until they return to the starting point. Along the way, you might encounter various events that twists and turns to your adventure.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://www.google.com",
    hostedLink: "https://www.google.com",
    techStack: ["java", ""],
    roles: [""],
    teamSize: 2,
    highlight: true,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
  {
    title: "The Path of Japan",
    description:
      "A thrilling command-line based adventure game that takes you on a journey through various locations in Japan.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://www.google.com",
    hostedLink: "https://www.google.com",
    techStack: ["python"],
    roles: [""],
    teamSize: 2,
    highlight: true,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
  {
    title: "Rate Van Rent",
    description:
      "A web application to help renters in Vancouver find more information regarding better housing options by providing visigility from other renters regarding their experiences.",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://www.google.com",
    hostedLink: "https://www.google.com",
    techStack: ["html", "css", "firebase", "firestore", "bootstrap"],
    roles: [""],
    teamSize: 3,
    highlight: true,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
  {
    title: "Dinosaur Hangman",
    description: "Description 1",
    date: "2025/06",
    image: "image1.jpg",
    gitHubLink: "https://www.google.com",
    hostedLink: "https://www.google.com",
    techStack: ["html", "scss", "js", "jquery"],
    roles: [""],
    teamSize: 1,
    highlight: false,
    whatIDid: [
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
      "asdk cksalw vkalsdofas lkcso asocw aosckos",
    ],
  },
];

export default PROJECT_CONTENT;
